import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Sidebar from "@/components/Sidebar/Sidebar";
import Loading from "./loading";
import { LoadingProvider } from "@/contexts/LoadingContext";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LoadingProvider>
      <html lang="en">
        <body className={`${inter.className} flex-container `}>
          <Sidebar />
          <Loading />
          <div className="main-container">
            <Header />
            <main>{children}</main>
          </div>
        </body>
      </html>
    </LoadingProvider>
  );
}
