import { Appointment } from "@/types/types";

export const appointments: Appointment[] = [
  {
    id: "91",
    doctor_id: "1",
    patient_id: "101",
    prescription_id: "19",
    date: "2023-09-18",
    time: "10:30 AM",
    reason: "Routine Checkup",
    consultationType: "Clinic Consulting",
    status: "Completed",
    duration: 30,
    diseaseDiagnosis: ["Asthma", "Type 2 Diabetes"],
    note: "Avoid sun exposure and use moisturizer.",
  },
  {
    id: "92",
    doctor_id: "1",
    patient_id: "102",
    prescription_id: "20",
    date: "2024-10-04",
    time: "09:00 AM",
    reason: "Neurological Assessment",
    consultationType: "Video Consulting",
    status: "Completed",
    duration: 45,
    diseaseDiagnosis: ["Asthma", "Type 2 Diabetes"],
    note: "Avoid sun exposure and use moisturizer.",
  },
  {
    id: "93",
    doctor_id: "1",
    patient_id: "103",
    prescription_id: "21",
    date: "2024-09-08",
    time: "11:15 AM",
    reason: "Skin Rash Consultation",
    consultationType: "Clinic Consulting",
    status: "Cancelled",
    duration: 20,
  },
  {
    id: "94",
    doctor_id: "1",
    patient_id: "104",
    prescription_id: "22",
    date: "2024-09-09",
    time: "08:45 AM",
    reason: "Child Immunization",
    consultationType: "Clinic Consulting",
    status: "Pending",
    duration: 25,
  },
  {
    id: "95",
    doctor_id: "1",
    patient_id: "105",
    prescription_id: "23",
    date: "2024-09-10",
    time: "02:00 PM",
    reason: "Knee Pain Consultation",
    consultationType: "Video Consulting",
    status: "Pending",
    duration: 30,
  },
  {
    id: "96",
    doctor_id: "1",
    patient_id: "101",
    date: "2024-09-10",
    time: "01:30 PM ",
    reason: "Follow-up for Hypertension",
    consultationType: "Clinic Consulting",
    status: "Completed",
    duration: 30,
    diseaseDiagnosis: ["Asthma", "Type 2 Diabetes"],
    note: "Avoid sun exposure and use moisturizer.",
  },
  {
    id: "97",
    doctor_id: "1",
    patient_id: "102",
    prescription_id: "",
    date: "2024-09-08",
    time: "11:30 AM",
    reason: "Coronary Artery Disease Management",
    consultationType: "Clinic Consulting",
    status: "Pending",
    duration: 45,
  },
  {
    id: "98",
    doctor_id: "1",
    patient_id: "103",
    date: "2024-09-09",
    time: "03:00 PM",
    reason: "Epilepsy Medication Adjustment",
    consultationType: "Video Consulting",
    status: "Completed",
    duration: 30,
    diseaseDiagnosis: ["Asthma", "Type 2 Diabetes"],
    note: "Avoid sun exposure and use moisturizer.",
  },
  {
    id: "99",
    doctor_id: "1",
    patient_id: "104",
    date: "2024-09-10",
    time: "06:45 PM",
    reason: "Migraine Treatment",
    consultationType: "Clinic Consulting",
    status: "Pending",
    duration: 30,
  },
  {
    id: "100",
    doctor_id: "1",
    patient_id: "105",
    date: "2024-09-11",
    time: "02:00 PM",
    reason: "Eczema Treatment",
    consultationType: "Clinic Consulting",
    status: "Cancelled",
    duration: 20,
  },
  {
    id: "101",
    doctor_id: "1",
    patient_id: "106",
    date: "2024-09-09",
    time: "01:00 PM",
    reason: "Acne Treatment",
    consultationType: "Clinic Consulting",
    status: "Completed",
    duration: 25,
  },
  {
    id: "102",
    doctor_id: "1",
    patient_id: "107",
    date: "2024-09-10",
    time: "08:30 AM",
    reason: "Asthma Control",
    consultationType: "Clinic Consulting",
    status: "Completed",
    duration: 30,
  },
  {
    id: "103",
    doctor_id: "1",
    patient_id: "108",
    date: "2024-09-11",
    time: "09:45 AM",
    reason: "Seasonal Allergies Management",
    consultationType: "Video Consulting",
    status: "Pending",
    duration: 30,
  },
  {
    id: "104",
    doctor_id: "1",
    patient_id: "109",
    date: "2024-09-10",
    time: "11:00 AM",
    reason: "Osteoarthritis Follow-Up",
    consultationType: "Clinic Consulting",
    status: "Cancelled",
    duration: 30,
  },
  {
    id: "105",
    doctor_id: "1",
    patient_id: "110",
    date: "2024-09-09",
    time: "01:15 PM",
    reason: "Rheumatoid Arthritis Treatment",
    consultationType: "Clinic Consulting",
    status: "Pending",
    duration: 45,
  },
];
