export const medicalRecords = [
  {
    patient_id: "101",
    doctor_id: "1",
    diagnosis: "Hyperlipidemia",
    treatment_plan: "Dietary changes, regular exercise, and medication",
    date_of_visit: "2024-08-11",
    follow_up: "2024-09-10",
    comments: "Patient is responding well to treatment.",
  },
  {
    patient_id: "102",
    doctor_id: "2",
    diagnosis: "Generalized Anxiety Disorder",
    treatment_plan: "Cognitive behavioral therapy and medication",
    date_of_visit: "2024-08-12",
    follow_up: "2024-08-26",
    comments: "Patient should monitor symptoms and report any changes.",
  },
  {
    patient_id: "103",
    doctor_id: "3",
    diagnosis: "Contact Dermatitis",
    treatment_plan: "Topical corticosteroids and avoid irritants",
    date_of_visit: "2024-08-13",
    follow_up: "2024-08-20",
    comments: "Improvement noted; continue current regimen.",
  },
  {
    patient_id: "104",
    doctor_id: "4",
    diagnosis: "Routine Child Immunization",
    treatment_plan: "Scheduled vaccinations",
    date_of_visit: "2024-08-14",
    follow_up: "2024-12-14",
    comments: "No adverse reactions noted.",
  },
  {
    patient_id: "105",
    doctor_id: "5",
    diagnosis: "Osteoarthritis",
    treatment_plan: "Physical therapy and NSAIDs",
    date_of_visit: "2024-08-15",
    follow_up: "2024-09-15",
    comments: "Pain management plan discussed; continue exercises.",
  },
];
