export const users = [
  {
    id: "1",
    name: "Dr. John Doe",
    email: "johndoe@example.com",
    password: "securepassword123",
    phone: "+1-202-555-0173",
    profilePhoto:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzE0vPkVph68ihTur8fttQLnUxAPOoMdvoR_GsMCr1YxIBBg-EojgADAY&s=10",
    specialty: "Cardiologist",
    token: "mock-token-1a2b3c4d5e6f",
  },
  {
    id: "2",
    name: "Dr. Emily Rose",
    email: "emilyrose@example.com",
    password: "strongpassword456",
    phone: "+1-202-555-0156",
    profilePhoto: "https://example.com/photos/emilyrose.jpg",
    specialty: "Neurologist",
    token: "mock-token-7g8h9i0j1k2l",
  },
  {
    id: "3",
    name: "Dr. Michael Brown",
    email: "michaelbrown@example.com",
    password: "anotherpassword789",
    phone: "+1-202-555-0134",
    profilePhoto: "https://example.com/photos/michaelbrown.jpg",
    specialty: "Dermatolog",
    token: "mock-token-mn3o4p5q6r7s",
  },
  {
    id: "4",
    name: "Dr. Sarah White",
    email: "sarahwhite@example.com",
    password: "supersecretpass",
    phone: "+1-202-555-0199",
    profilePhoto: "https://example.com/photos/sarahwhite.jpg",
    specialty: "Pediatrics",
    token: "mock-token-t8u9v0w1x2y3z",
  },
  {
    id: "5",
    name: "Dr. James Green",
    email: "jamesgreen@example.com",
    password: "password321",
    phone: "+1-202-555-0145",
    profilePhoto: "https://example.com/photos/jamesgreen.jpg",
    specialty: "Orthopedics",
    token: "mock-token-4a5b6c7d8e9f",
  },
];
